# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='desc',
            field=models.CharField(default='desc', max_length=100, verbose_name='描述'),
        ),
    ]
