# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-31 21:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_siteconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='博客站长'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_owner_desc',
            field=mdeditor.fields.MDTextField(max_length=256, verbose_name='站长介绍'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_owner_friends',
            field=models.TextField(help_text='友链的地址,使用;隔开', verbose_name='友链地址'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_owner_github_addr',
            field=models.URLField(verbose_name='github地址'),
        ),
    ]
