# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-31 21:49
from __future__ import unicode_literals

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_auto_20200131_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='site_owner_desc',
            field=mdeditor.fields.MDTextField(verbose_name='站长介绍'),
        ),
    ]
