# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-31 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20200131_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='icon',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
