# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-31 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_siteconfig_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_owner_desc_short',
            field=models.CharField(default=1, max_length=256, verbose_name='简述'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='icon',
            field=models.ImageField(upload_to='', verbose_name='头像'),
        ),
    ]
