# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-12 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20200131_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='icon',
            field=models.ImageField(default='user_icon.png', upload_to='', verbose_name='头像'),
        ),
    ]
