# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-01-29 12:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200115_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Categories',
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': '分类表', 'verbose_name_plural': '分类表'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='categories',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
    ]
