# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-07 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20200407_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
    ]
