# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-04-15 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20200412_1648'),
        ('article', '0016_remove_article_tags'),
    ]

    operations = [
    ]
